controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_controller:
      type: swerve_controller/SwerveController

joint_state_broadcaster:
  ros__parameters:
    extra_joints: [      ]

swerve_controller:
  ros__parameters:
    front_left_wheel_joint: "front_left_wheel_joint"
    front_right_wheel_joint: "front_right_wheel_joint"
    rear_left_wheel_joint: "rear_left_wheel_joint"
    rear_right_wheel_joint: "rear_right_wheel_joint"
    front_left_axle_joint: "front_left_axle_joint"
    front_right_axle_joint: "front_right_axle_joint"
    rear_left_axle_joint: "rear_left_axle_joint"
    rear_right_axle_joint: "rear_right_axle_joint"
    chassis_center_to_axle: 0.145
    axle_center_to_wheel: 0.128
    wheel_radius: 0.0508

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
