<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PLACEHOLDER VALUES! CHANGE THESE -->
    <xacro:property name="total_length" value="1" />
    <xacro:property name="total_width" value="1" />
    <xacro:property name="total_height" value="1" />
    <xacro:property name="total_weight" value="1" />

    <xacro:property name="bar_height" value="1" />
    <xacro:property name="bar_width" value="1" />

    <!-- This entire file is pretty much a placeholder -->
    <!-- Feel free to delete everything and start over -->
    <xacro:macro name="base_stage" params="prefix">
        <link name="base_link"></link>
        <link name="base_stage_link">
            <xacro:inertial_box mass="${total_weight}" x="${total_length}" y="${total_width}" z="${total_height}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_box>
            <visual>
                <origin  xyz="0 0 ${total_height/2}" rpy="0 -${pi/2} -${pi/2}"  />
                <geometry>
                    <mesh filename="package://elevator_bot_description/meshes/BaseStageStructure.stl" scale="0.001 0.001 0.001" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${total_length} ${total_height} ${total_width}" />
                </geometry>
            </collision>
        </link>
        <joint name="base_stage_joint" type="fixed">
            <parent link="base_link" />
            <child link="base_stage_link" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>
        <joint name="base_stage_joint" type="prismatic">
            <parent link="base_stage_link"/>
            <child link="second_stage_link" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
</robot>