<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 2in (0.0508m) line height -->
    <!-- 1in (0.0254m) line width -->
    <!-- 15.5 (0.3937m) width total -->
    <!-- 47in (1.1938m) length total -->
    <!-- 4.9748lbs (2.2565kgs) weight total -->

    <xacro:macro name="second_stage" params="prefix">
        <!-- Second Stage Properties -->
        <link name="second_stage"></link>

        <xacro:property name="total_length" value="1.1938" />
        <xacro:property name="total_width" value="0.3937" />
        <xacro:property name="total_height" value="0.0508" /> <!-- Not completely accurate!-->
        <xacro:property name="weight" value="2.2565" />

        <xacro:property name="bar_height" value="0.0508" />
        <xacro:property name="bar_width" value="0.0254" />


        <xacro:inertial_box mass="${total_weight}" x="${total_length}" y="${total_width}" z="${total_height}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://elevator_bot_description/meshes/2ndStageStructure.stl" scale="0.1 0.1 0.1"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 ${total_height/2} 0" rpy="0 0 0" />
            <geometry>
                <box size="${total_length} ${total_height} ${total_width}" />
            </geometry>
        </collision>
    </xacro:macro>

</robot>